# Generated by Django 4.1.5 on 2023-03-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('transport_mode', models.CharField(max_length=100)),
                ('hotel_type', models.CharField(max_length=100)),
                ('flight_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_rental_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('train_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
